{% set python_min = "3.10" %}
{% set name = "ansys-geometry-core" %}
{% set version = "0.14.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ansys_geometry_core-{{ version }}.tar.gz
  sha256: 2ba50961138c7093f6f8b0be13786a22a7dd0d5acdda6c78bc8d4d1345abe81d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.2,<4
    - pip
  run:
    - python >={{ python_min }},<4.0
    - ansys-api-discovery ==1.0.20
    - ansys-tools-common >=0.3,<1
    - ansys-tools-visualization-interface >=0.2.6,<1
    - beartype >=0.11.0,<0.23
    - grpcio >=1.35.0,<2
    - grpcio-health-checking >=1.45.0,<2
    - matplotlib >=3,<4
    - numpy >=1.20.3,<3
    - pint >=0.18,<1
    - protobuf >=3.20.2,<7
    - pyvista >=0.38.1,<1
    - requests >=2,<3
    - scipy >=1.7.3,<2
    - semver >=3,<4
    - six >=1.16.0,<2
    - vtk >=9,<10

test:
  imports:
    - ansys.geometry.core
  commands:
  # Disabled until https://github.com/conda-forge/vtk-feedstock/pull/324 is solved
  #   - pip check
    - pip list
    - python -c "from ansys.geometry.core import __version__; print(__version__)"
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: A Python wrapper for Ansys Geometry services
  dev_url: https://github.com/ansys/pyansys-geometry
  home: https://pypi.org/project/ansys-geometry-core/
  doc_url: https://geometry.docs.pyansys.com/
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - RobPasMue
    - AlejandroFernandezLuces
